### ISSUE TITLE
Option for the fake time to progress

### ISSUE THREAD

**Issue by marcusbuffett** [cpulvermacher/time-travel#10]
It would be awesome if the fake time would progress once the page reloads, as an option.

This tool has been super useful for testing stuff, really appreciate that you made this!

**Comment by cpulvermacher** [comment]
That does sound like a useful addition. Do you have a particular case where a static time just doesn't do?

Also, thanks for the feedback! Glad to hear it's useful! :slightly_smiling_face:

**Comment by marcusbuffett** [comment]
> That does sound like a useful addition. Do you have a particular case where a static time just doesn't do?

I do, yeah. I use your plugin to fake the time so I can test out what our drop pages at opensea look like during different stage, so like we can go to [a page like this](https://opensea.io/collection/invisible-friends-physical-collectibles/drop) and fake the time to be during one of the stages to see what the UI will look like.

What I wanted to use a progressing time to check out is whether we correctly transition to the next stage, so I would set the time to the time of the next stage - 1 minute, then wanted to see if our logic to update the stages would work. We basically set a timeout with the difference then re-calculate which stage is active using `Date.now()`. But of course with a static time when the timeout happens it'll just see the same time as before, so the current stage stays the same.

Hopefully that makes sense!

**Comment by cpulvermacher** [comment]
Thanks for the explanation. Will consider adding it in the next version!

**Comment by cpulvermacher** [comment]
I've prepared a branch that includes a feature to tick the time forward: https://github.com/cpulvermacher/time-travel/tree/tick-clock

If you would like to give it a try first, you can follow the instructions in https://github.com/cpulvermacher/time-travel/tree/tick-clock#installation to build and install a local version. Would love to hear your thoughts :)

**Comment by cpulvermacher** [comment]
Fixed in version 0.0.9
